### PR TITLE
add u-gap-xs

### PR DESCRIPTION
**Pull request by maltoe**
👋

### CODE REVIEW

**Review by planktonic — COMMENTED** [review]
Interesting! What’s the use case, is it a general enough need to be made default?

**Comment by maltoe** [comment]
> Interesting! What’s the use case, is it a general enough need to be made default?

I don't know. Thought it was more of an "omission". use-case is the buttons in the project-whose-name-we-don't-say, in the tables. Found the `s` gap a bit too wide, `xs` also gives more room for actual content in the table.

**Comment by planktonic** [comment]
Ok yeh that’s reasonable :+1: I’ll take a look again and look to get this merged

**Review by planktonic — APPROVED** [review]
Thanks for the addition! ✨

**Pull request merged**
