### PR TITLE
[#164] add ci tests

### PR DESCRIPTION
**Pull request by planktonic**
### Summary

Partial fix for #164.

The following changes are contained in this pull request:
- Initial `.travis.yml`, currently just running `npm run lint` and `npm run build`.

### Linting and testing
- [x] `npm run checks` script has been run without errors

### CODE REVIEW

**Comment by planktonic** [comment]
Partial fix for #164 because running the visual regression tests via travis is not simple! Any advice welcome — the problem is not being able to run the styleguide server on travis. Could be done with a hosted styleguide (would mean deploying branches to a styleguide server at the same time), or ngrok to a local box…

**Comment by pmeinhardt** [comment]
Can you just render out the styleguide-server generated pages/individual components to image files in a separate step beforehand and then run the visual regression tests on those? That's what's more difficult on Travis CI, right?

Running on Travis will likely require Xvfb (virtual framebuffer) or something similar.

**Comment by planktonic** [comment]
Our current setup: the styleguide creates the pages from parsing our Sass & the comments therein. The VRT app visits each styleguide URL we specify, uses phantom to render screenshots, then compares them to the checked-in originals.

The hard part is running the styleguide at an accessible URL in order that the VRT can use phantom to render it to images (by all accounts phantom is not a big problem on travis). Also, how do we to specify URLs in such a way as it works both locally and via travis without maintaining separate versions?

Perhaps we chat about this when you have time?

**Comment by pmeinhardt** [comment]
Yup, let's stick our heads together to figure out a solution 👍

**Comment by planktonic** [comment]
In order to get this first step of travis configuration on master I’ll merge this now, and revisit the styleguide question in a new PR

**Pull request merged**
